pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                // Confirm the scripts directory exists and list its contents
                bat 'dir scripts'
                
                // Execute the deliver.bat script
                bat 'scripts\\deliver.bat' // Use backslash for Windows paths
            }
        }
    }
}
